version: "3.9"
volumes:
  volume1:
services:
  zookeeper:
    image: zookeeper:3.9.1-jre-17
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_container
    volumes:
      - ./server.properties:/opt/bitnami/kafka/config/server.properties
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CREATE_TOPICS=__consumer_offsets:1:1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes