spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cars
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  application:
    name: cars
server:
  servlet:
    context-path: /api/cars/
  port: 8081

gateway: http://localhost:8080